from app import create_app
from models import db, FAQ, Policy, KnowledgeBaseEntry, Document
from datetime import datetime

app = create_app()
with app.app_context():
    db.create_all()

    faqs = [
        ("What are the entry requirements for undergraduate programs?", "Undergraduate applicants must have a minimum of 5 O'Level credits including English and Mathematics, plus a relevant A'Level qualification or equivalent. Specific programs may have additional subject requirements. Check the admissions page for department-specific criteria.", "admissions"),
        ("When is the application deadline for the next academic year?", "The main application deadline is typically June 30 for the fall semester. Late applications may be considered on a space-available basis until August 15. Visit the admissions portal for exact dates and rolling admissions policies.", "admissions"),
        ("How do I apply for a scholarship?", "Complete the scholarship application form on the student portal before the deadline. You will need your academic transcript, personal statement, and two reference letters. Merit-based scholarships are awarded automatically based on entrance grades; need-based scholarships require a separate financial aid application.", "scholarships"),
        ("What is the tuition fee for the current academic year?", "Tuition varies by program. Full-time undergraduate programs are typically $3,500 per semester for in-state students and $7,200 for out-of-state students. Graduate programs range from $4,000 to $8,000 per semester. Check the bursary website for the latest fee schedule.", "fees"),
        ("When is the fee payment deadline?", "Full payment or a minimum of 60% of tuition is due two weeks before the semester starts. The exact deadline is posted on the academic calendar. Late payments incur a 2% penalty per week. Payment plans are available through the bursary office.", "fees"),
        ("How do I register for courses?", "Log in to the student portal, go to Course Registration, select the semester, and add courses from the approved list. Meet with your academic advisor before registering to ensure prerequisites are met. Registration closes on the first day of classes.", "registration"),
        ("What is the add/drop period?", "The add/drop period runs through the first week of the semester. You may add courses if seats are available and drop courses without academic penalty. After the first week, drops are recorded on your transcript. Changes require advisor approval for full-time status maintenance.", "registration"),
        ("When are final exams scheduled?", "Final exams are held during the last two weeks of each semester. The exam timetable is published three weeks before exams begin. Check the registrar's website or student portal for your personalized schedule. Travel plans should not conflict with exam dates.", "exams"),
        ("How can I check my grades and transcript?", "Grades are posted to the student portal within five business days after the final exam. To request an official transcript, submit a transcript request form through the registrar's office or student portal. Unofficial transcripts are available immediately online.", "results"),
        ("How do I request my graduation clearance?", "Visit the registrar's office with your completed clearance form. You must settle all outstanding fees, return library books, and obtain signatures from the bursary, library, and department. Clearance typically takes 2-3 business days once all requirements are met.", "graduation"),
        ("Where can I find my class timetable?", "Class timetables are available on the student portal under Academics > Timetable. You can filter by program, semester, and course level. Timetable changes due to room reassignments are posted at least 48 hours in advance.", "academics"),
        ("What are the library opening hours?", "The main library is open Monday-Friday 8:00 AM to 10:00 PM, Saturday 9:00 AM to 6:00 PM, and Sunday 12:00 PM to 8:00 PM. Special hours during exam periods and holidays are posted on the library website.", "facilities"),
        ("How do I get a student ID card?", "Visit the student affairs office with your admission letter and a passport photo. ID cards are issued free of charge upon initial enrollment. Replacement cards for lost or damaged IDs cost $15 and can be requested online.", "student-services"),
        ("Who is my academic advisor?", "Each student is assigned an academic advisor from their department during orientation. Advisor assignments are listed on the student portal under Academics > Advisor. You may request a change through the department office if needed.", "academics"),
        ("What happens if I miss an exam?", "If you miss an exam due to illness or emergency, submit a petition to the registrar's office within 48 hours with supporting documentation. A makeup exam may be scheduled. Unauthorized absences result in a zero for that exam.", "exams"),
        ("How do I appeal a grade?", "First discuss the grade with your instructor. If unresolved, submit a formal grade appeal to the department head within 10 business days of grade posting. Include the course outline, graded work, and a written explanation. The department will review and respond within 15 business days.", "results"),
        ("What is the minimum GPA to remain in good standing?", "Undergraduate students must maintain a cumulative GPA of at least 2.0. Graduate students must maintain a 3.0 GPA. Students below the threshold are placed on academic probation and have one semester to improve or face dismissal.", "academics"),
        ("How do I apply for on-campus housing?", "Submit a housing application through the student portal before the deadline. Priority is given to first-year and transfer students. Room assignments are based on application date and preferences. Housing contracts are for the full academic year.", "hostel"),
        ("What items are allowed in the dormitory?", "Allowed items include a mini-fridge (max 4.5 cubic feet), microwave, television, laptop, small cooking appliances, and personal furniture. Prohibited items include space heaters, halogen lamps, candles, and pets. See the housing handbook for the complete list.", "hostel"),
        ("How do I report a maintenance issue in my dorm?", "Report maintenance issues through the housing portal or by contacting the resident assistant. Emergency issues like leaks or electrical problems should be reported immediately by phone. Non-emergency requests are typically resolved within 3 business days.", "hostel"),
        ("What financial aid options are available?", "Options include federal grants, need-based scholarships, work-study programs, and student loans. Complete the FAFSA form to determine eligibility for need-based aid. The financial aid office can help you find external scholarships as well.", "scholarships"),
        ("How do I withdraw from a course?", "Submit a course withdrawal form through the registrar's office or student portal before the withdrawal deadline. Withdrawals after the add/drop period may result in a 'W' on your transcript. Consult your advisor before withdrawing to understand the impact on financial aid and progress.", "registration"),
        ("What is the maximum course load per semester?", "Full-time students may take up to 18 credit hours per semester without special permission. Overloads up to 21 hours require dean approval. Part-time students may take up to 11 credit hours. Check your program requirements for recommended course loads.", "registration"),
        ("How do I join a student club or organization?", "Browse available clubs on the student activities portal. Attend the club fair at the beginning of each semester or contact the club directly. Some clubs require an application or auditions. Membership is free for most organizations.", "student-life"),
        ("Where can I get help with writing assignments?", "The writing center offers free one-on-one tutoring for essays, research papers, and presentations. Drop in during operating hours or schedule an appointment online. They can help with structure, citations, and grammar at any stage of the writing process.", "academics"),
        ("What career services are available?", "The career center provides resume reviews, mock interviews, job boards, and career counseling. They also host employer recruitment events and graduate school fairs. All services are free for current students and recent graduates.", "career"),
        ("How do I request a leave of absence?", "Submit a leave of absence form to the registrar's office. Medical leaves require a doctor's note. Personal leaves may be granted for up to one semester. Students on leave retain their admission status but must re-register before returning.", "academics"),
        ("What is the policy on academic dishonesty?", "Academic dishonesty includes plagiarism, cheating, falsification of data, and unauthorized collaboration. Penalties range from a zero on the assignment to course failure or expulsion. All violations are reported to the academic affairs office and recorded on the student's disciplinary file.", "policies"),
        ("How do I access my student email?", "Your student email is firstname.lastname@university.edu. Access it through the student portal or set it up on your mobile device. Check your email daily for important announcements from the registrar, bursary, and department.", "student-services"),
        ("What health services are available on campus?", "The campus health center provides primary care, mental health counseling, and pharmacy services. Most services are covered by the student health fee. Appointments can be scheduled online or by phone. Emergency cases are seen immediately.", "facilities"),
        ("How do I update my contact information?", "Update your address, phone number, and emergency contact through the student portal under Profile Settings. Changes take effect immediately. It is your responsibility to keep your contact information current for important notifications.", "student-services"),
        ("When does the fall semester start and end?", "The fall semester typically begins in late August and ends in mid-December. Specific dates are on the academic calendar. Orientation for new students is held one week before classes begin.", "academics"),
        ("What is the grading scale?", "The standard grading scale is A (90-100), B (80-89), C (70-79), D (60-69), and F (below 60). Some courses use pass/fail grading. Incomplete grades must be resolved within one semester or they convert to an F.", "academics"),
        ("How do I apply for a transfer?", "Submit a transfer application through the admissions portal. Transfer students must have completed at least 12 college-level credits with a minimum GPA of 2.5. Official transcripts from all previously attended institutions are required.", "admissions"),
        ("What parking options are available on campus?", "Student parking permits are available for commuter and residential students. Daily parking is also available in visitor lots. Parking permits are sold on a first-come, first-served basis. Electric vehicle charging stations are located in parking lot C.", "facilities"),
    ]

    for q, a, cat in faqs:
        faq = FAQ(question=q, answer=a, category=cat, is_active=True)
        db.session.add(faq)

    policies = [
        ("Academic Integrity Policy", "All students are expected to uphold the highest standards of academic integrity. Plagiarism, cheating, fabrication of data, and unauthorized collaboration are strictly prohibited. Violations will result in disciplinary action ranging from a failing grade to expulsion. The university uses plagiarism detection software to screen submitted work. Students are responsible for understanding and complying with the academic integrity policy.", "academic"),
        ("Attendance Policy", "Students are expected to attend all scheduled classes. Attendance below 75% may result in academic penalties, including grade reductions or course failure. Instructors may take attendance at each class. Excused absences require advance approval or post-absence documentation for medical or emergency reasons.", "academic"),
        ("Grading and Transcript Policy", "Final grades are submitted by instructors within five business days after the final exam. Grades become part of the official transcript and cannot be changed after one semester unless there was a documented clerical error. Grade appeals must follow the formal grievance procedure. Transcript requests are processed within 3-5 business days.", "academic"),
        ("Student Conduct Policy", "Students must conduct themselves in a manner that respects the rights and property of others. Prohibited conduct includes harassment, vandalism, theft, and disruption of university activities. Violations are adjudicated by the student conduct office and may result in suspension or expulsion. All students are bound by the code of conduct.", "conduct"),
        ("Privacy and Data Protection Policy", "The university collects and uses student data in accordance with applicable privacy laws. Student records are confidential and may only be released with written consent or as required by law. Students may inspect their records by submitting a request to the registrar's office. Directory information may be released unless the student opts out.", "administrative"),
        ("Financial Aid Satisfactory Academic Progress Policy", "To maintain financial aid eligibility, students must complete at least 67% of attempted credits and maintain a minimum GPA of 2.0. Dropping below these standards results in financial aid suspension. Students may appeal by submitting a written explanation and an academic plan to the financial aid office.", "financial"),
        ("Refund Policy for Tuition and Fees", "Full refunds are issued if a course is dropped before the semester starts. A 75% refund is available during the add/drop period. No refunds are given after the first week of classes. Refunds are processed within 14 business days to the original payment method. Non-refundable fees include technology and activity fees.", "financial"),
        ("Campus Safety and Security Policy", "The university provides 24-hour campus security, emergency call boxes, and escort services. All crimes and safety concerns should be reported to campus security immediately. The annual security report is available on the university website. Students are encouraged to register their emergency contacts in the alert system.", "safety"),
        ("IT and Acceptable Use Policy", "University IT resources are provided for academic and administrative purposes. Prohibited activities include unauthorized access, distribution of malware, and copyright infringement. Network usage may be monitored for security purposes. Violations may result in loss of IT privileges and disciplinary action.", "administrative"),
        ("Equal Opportunity and Non-Discrimination Policy", "The university prohibits discrimination based on race, color, national origin, sex, age, disability, religion, sexual orientation, or gender identity. Complaints of discrimination should be reported to the equal opportunity office. Retaliation against complainants is strictly prohibited.", "conduct"),
    ]

    for title, content, cat in policies:
        policy = Policy(title=title, content=content, category=cat, is_active=True)
        db.session.add(policy)

    knowledge_entries = [
        ("How to apply for admission", "To apply for admission, create an account on the admissions portal, complete the online application form, upload your academic transcripts and supporting documents, and pay the application fee. Track your application status through the portal. Admission decisions are typically released within 4-6 weeks after the deadline.", "admissions", "How do I apply to the university", "application process, admission requirements", "Check application status, admission decision"),
        ("Where to pay school fees", "Pay school fees through the student portal using a credit card, debit card, or bank transfer. You can also pay in person at the bursary office or at any approved bank branch. Keep your payment receipt for verification. Fees must be paid before the semester starts to avoid penalties.", "fees", "How do I pay my school fees", "payment, bursary, fee payment", "Payment methods, payment deadline"),
        ("Tuition fee payment deadline", "Tuition fees must be paid by the deadline published on the academic calendar. A minimum of 60% is due two weeks before the semester starts. Late payments incur a 2% penalty per week. Payment plans are available through the bursary office for students facing financial difficulties.", "fees", "When is the fee payment deadline", "payment deadline, tuition due date", "Late payment penalty, payment plan"),
        ("What are the admission requirements", "Undergraduate applicants need at least 5 O'Level credits including English and Mathematics, plus A'Level qualifications. Graduate applicants need a bachelor's degree in a related field with a minimum GPA of 2.5. International students must also demonstrate English proficiency through TOEFL or IELTS scores. Specific programs may have additional requirements.", "admissions", "What are the admission requirements", "entry requirements, qualifications", "Undergraduate requirements, graduate requirements"),
        ("How to get graduation clearance", "To get graduation clearance, complete the clearance form available on the student portal. Settle all outstanding fees, return all library books, and obtain clearance signatures from the bursary, library, and your department. Submit the completed form to the registrar's office. Processing takes 2-3 business days.", "graduation", "How do I get clearance for graduation or final year", "graduation clearance, final year", "Graduation requirements, clearance process"),
        ("How to register courses", "Log in to the student portal, select Course Registration, choose the semester, and add courses from the available list. Ensure you meet all prerequisites and have advisor approval. You may register for up to 18 credit hours without special permission. Registration closes on the first day of classes.", "registration", "How do I register for courses", "course registration, enrollment", "Registration deadline, credit hours"),
        ("When is the semester start date", "The fall semester starts in late August and the spring semester starts in early January. Exact dates are published on the academic calendar. Orientation for new students begins one week before classes start. Check the student portal for any schedule changes due to holidays or weather.", "academics", "When does the semester start", "semester dates, academic calendar", "Fall semester, spring semester, term dates"),
        ("How to request transcript", "Request an official transcript through the student portal or in person at the registrar's office. Unofficial transcripts are available immediately online. Official transcripts are processed within 3-5 business days and cost $5 per copy. Transcripts will not be released if you have outstanding financial obligations to the university.", "results", "How do I request my transcript", "transcript request, academic records", "Official transcript, unofficial transcript"),
        ("Student portal login help", "If you cannot log in to the student portal, use the 'Forgot Password' link to reset your password using your registered email. If that does not work, contact IT support at support@university.edu or visit the help desk in the library. Ensure you are using the correct student ID and password.", "student-services", "How do I log in to the student portal", "portal login, student portal help", "Password reset, IT support"),
        ("Hostel accommodation booking", "Book on-campus accommodation through the housing portal. Priority is given to first-year students and those with special needs. Complete the housing application, pay the security deposit, and select your room preferences. Housing contracts run for the full academic year and include utilities and internet access.", "hostel", "How do I apply for on-campus housing", "hostel booking, accommodation", "Dormitory, residence hall, housing contract"),
        ("Library borrowing rules", "Undergraduate students may borrow up to 10 books for 14 days. Graduate students may borrow up to 20 books for 30 days. Items may be renewed twice if not requested by another patron. Overdue items incur fines of $1 per day. Reference materials and reserves cannot be borrowed.", "library", "What are the library borrowing rules", "library rules, borrowing books", "Due dates, overdue fines"),
        ("Exam timetable and schedule", "The exam timetable is published three weeks before the exam period on the registrar's website and student portal. Exams are held in the last two weeks of the semester. Check your personalized schedule regularly for room assignments and time changes. Arrive at least 15 minutes early on exam day.", "exams", "When are final exams scheduled", "exam timetable, exam schedule", "Exam dates, exam locations"),
        ("Scholarship application process", "Merit-based scholarships are awarded automatically based on admission credentials. Need-based scholarships require a separate FAFSA submission and scholarship application. Application deadlines vary. Maintain the required GPA to keep your scholarship. Scholarships may be renewed annually based on continued eligibility.", "scholarships", "How do I apply for a scholarship", "scholarship application, financial aid", "Merit scholarship, need-based aid"),
        ("Academic calendar important dates", "Key dates include registration periods, add/drop deadlines, midterm exams, Thanksgiving break, final exams, and graduation ceremonies. The academic calendar is available on the registrar's website and should be reviewed at the start of each semester. Changes to the calendar are communicated through official university channels.", "academics", "What are the important dates in the academic calendar", "academic calendar, semester dates", "Registration dates, exam dates, holidays"),
        ("How to drop or add a course", "Add courses during the add/drop period through the student portal. Drop courses before the withdrawal deadline to avoid academic penalties. After the add/drop period, drops result in a 'W' on your transcript. Consult your advisor before making changes to ensure you maintain full-time status and progress toward your degree.", "registration", "How do I add or drop a course", "add/drop, course withdrawal", "Withdrawal deadline, full-time status"),
        ("Minimum GPA requirement", "Undergraduate students must maintain a cumulative GPA of 2.0 or higher. Graduate students must maintain a 3.0 GPA. Students who fall below these thresholds are placed on academic probation for one semester. If the GPA does not improve, the student may be dismissed from the program. Academic advisors monitor student progress.", "academics", "What is the minimum GPA requirement", "GPA requirement, academic standing", "Academic probation, good standing"),
        ("How to apply for on-campus job", "On-campus job openings are posted on the student portal and career center website. Positions are available in dining services, library, IT, administrative offices, and research labs. Submit an online application and resume. Work-study students receive priority consideration. Most positions offer flexible hours around class schedules.", "career", "How do I apply for an on-campus job", "on-campus job, work study", "Student employment, part-time job"),
        ("Campus map and directions", "The campus map is available on the university website and mobile app. Buildings are numbered by zone: academic buildings are in zones A and B, residence halls in zones C and D, and athletic facilities in zone E. Main parking lots are P1 through P5. Campus tours are offered daily at 10:00 AM and 2:00 PM.", "facilities", "Where is the campus located", "campus map, directions", "Building locations, parking"),
        ("How to change my major", "Submit a change of major form through the student portal or registrar's office. Some programs have specific GPA requirements or prerequisite courses. Changing to a high-demand major may require approval from the receiving department. The change takes effect the following semester unless special permission is granted.", "academics", "How do I change my major", "change of major, program change", "Major requirements, department approval"),
        ("Student health insurance", "All full-time students are automatically enrolled in the student health insurance plan. The cost is included in tuition unless you waive it with proof of comparable coverage. The plan covers preventive care, doctor visits, prescriptions, and emergency services. Visit the health center website for plan details and claim forms.", "health", "What is the student health insurance plan", "health insurance, student health", "Insurance waiver, health center"),
        ("Dormitory move-in dates", "New students move in during orientation week, typically one week before classes start. Returning students move in based on their housing assignment, usually two to three days before classes begin. Exact move-in dates and times are emailed to resident students. Early move-in may be available for an additional fee.", "hostel", "When is dormitory move-in", "move-in dates, residence move-in", "Housing assignment, early move-in"),
        ("How to appeal an admission decision", "If you believe your admission decision was made in error, submit a written appeal to the admissions office within 14 days of the decision. Include any new information or documentation that was not part of your original application. Appeals are reviewed by the admissions committee and decisions are final.", "admissions", "How do I appeal an admission decision", "admission appeal", "Appeal process, admissions review"),
        ("What is the withdrawal refund policy", "Full refund if withdrawal occurs before the semester starts. 75% refund during the add/drop period. 50% refund during weeks 2-4. No refund after week 5. Refunds are processed within 14 business days. Non-refundable fees include technology, activity, and orientation fees.", "financial", "What is the withdrawal and refund policy", "refund policy, withdrawal refund", "Refund percentage, refund timeline"),
        ("How to get disability accommodations", "Register with the disability services office to receive accommodations. Provide documentation of your disability and meet with a coordinator to develop an accommodation plan. Common accommodations include extended time on exams, note-taking assistance, and accessible classroom locations. Notify your instructors at the start of each semester.", "student-services", "How do I get disability accommodations", "disability services, accommodations", "Accessibility, exam accommodations"),
        ("Campus security emergency contacts", "For emergencies on campus, call campus security at the main line or 911 for life-threatening situations. Non-emergency reports can be made through the campus safety portal. Emergency alert notifications are sent via text, email, and the university app. The campus security office is located in the administration building.", "safety", "What are the campus security contacts", "emergency contacts, campus security", "Emergency phone, safety office"),
        ("How to get a part-time job off campus", "The career center maintains partnerships with local employers for internship and part-time opportunities. Attend career fairs and use the job board to find positions. International students must ensure employment complies with visa regulations. Resume and interview assistance is available through the career center.", "career", "How do I find a part-time job off campus", "off-campus job, part-time work", "Internship, career fair"),
        ("How to submit assignments online", "Submit assignments through the course learning management system before the deadline. Accepted formats include PDF, DOCX, and ZIP. Late submissions may receive a grade penalty unless an extension was granted. Keep a copy of your submission confirmation as proof of on-time submission.", "academics", "How do I submit assignments", "assignment submission, LMS", "Late submission, file formats"),
        ("What are the graduation requirements", "Complete all major and general education requirements, maintain the minimum GPA, complete at least 120 credit hours for undergraduate degrees, and clear all financial and disciplinary holds. Apply for graduation during your final semester. The graduation audit is conducted by the registrar's office.", "graduation", "What are the graduation requirements", "graduation requirements, degree requirements", "Credit hours, graduation audit"),
        ("How to contact the registrar", "The registrar's office is located in the administration building, room 101. Hours are Monday-Friday 8:00 AM to 5:00 PM. Call the main line or email registrar@university.edu. Online forms for transcript requests, enrollment verification, and degree audits are available on the registrar's webpage.", "student-services", "How do I contact the registrar", "registrar contact, registrar office", "Registrar hours, enrollment verification"),
    ]

    for q, a, cat, aliases, tags, related in knowledge_entries:
        entry = KnowledgeBaseEntry(
            title=q,
            question=q,
            answer=a,
            category=cat,
            aliases=aliases,
            tags=tags,
            related_questions=related,
            is_active=True
        )
        db.session.add(entry)

    db.session.commit()
    print("Seeded database with:")
    print(f"  FAQs: {FAQ.query.count()}")
    print(f"  Policies: {Policy.query.count()}")
    print(f"  Knowledge base entries: {KnowledgeBaseEntry.query.count()}")
